package mnj.mfg.model.views;

import mnj.mfg.model.entities.LineEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 02 13:40:19 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LinesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(LinesVORowImpl obj) {
                return obj.getDivisionId();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        HeaderId {
            public Object get(LinesVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(LinesVORowImpl obj) {
                return obj.getLineId();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(LinesVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        CutNumber {
            public Object get(LinesVORowImpl obj) {
                return obj.getCutNumber();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setCutNumber((String)value);
            }
        }
        ,
        NoOfPly {
            public Object get(LinesVORowImpl obj) {
                return obj.getNoOfPly();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setNoOfPly((String)value);
            }
        }
        ,
        AutoManual {
            public Object get(LinesVORowImpl obj) {
                return obj.getAutoManual();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAutoManual((String)value);
            }
        }
        ,
        StartTime {
            public Object get(LinesVORowImpl obj) {
                return obj.getStartTime();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setStartTime((Date)value);
            }
        }
        ,
        EndTime {
            public Object get(LinesVORowImpl obj) {
                return obj.getEndTime();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setEndTime((Date)value);
            }
        }
        ,
        MarkerId {
            public Object get(LinesVORowImpl obj) {
                return obj.getMarkerId();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setMarkerId((String)value);
            }
        }
        ,
        PlanYds {
            public Object get(LinesVORowImpl obj) {
                return obj.getPlanYds();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setPlanYds((String)value);
            }
        }
        ,
        PlanInch {
            public Object get(LinesVORowImpl obj) {
                return obj.getPlanInch();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setPlanInch((String)value);
            }
        }
        ,
        PlanMeter {
            public Object get(LinesVORowImpl obj) {
                return obj.getPlanMeter();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setPlanMeter((String)value);
            }
        }
        ,
        ActualYds {
            public Object get(LinesVORowImpl obj) {
                return obj.getActualYds();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setActualYds((String)value);
            }
        }
        ,
        ActualInch {
            public Object get(LinesVORowImpl obj) {
                return obj.getActualInch();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setActualInch((String)value);
            }
        }
        ,
        ActualMeter {
            public Object get(LinesVORowImpl obj) {
                return obj.getActualMeter();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setActualMeter((String)value);
            }
        }
        ,
        TimeCal {
            public Object get(LinesVORowImpl obj) {
                return obj.getTimeCal();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setTimeCal((String)value);
            }
        }
        ,
        UsedTimeInMinutes {
            public Object get(LinesVORowImpl obj) {
                return obj.getUsedTimeInMinutes();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setUsedTimeInMinutes((Date)value);
            }
        }
        ,
        Remarks {
            public Object get(LinesVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(LinesVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(LinesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(LinesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(LinesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(LinesVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Inches {
            public Object get(LinesVORowImpl obj) {
                return obj.getInches();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setInches((Number)value);
            }
        }
        ,
        Yards {
            public Object get(LinesVORowImpl obj) {
                return obj.getYards();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setYards((Number)value);
            }
        }
        ,
        cutNoLov1 {
            public Object get(LinesVORowImpl obj) {
                return obj.getcutNoLov1();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Auto_manul1 {
            public Object get(LinesVORowImpl obj) {
                return obj.getAuto_manul1();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        markeridLOV1 {
            public Object get(LinesVORowImpl obj) {
                return obj.getmarkeridLOV1();
            }

            public void put(LinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(LinesVORowImpl object);

        public abstract void put(LinesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int CUTNUMBER = AttributesEnum.CutNumber.index();
    public static final int NOOFPLY = AttributesEnum.NoOfPly.index();
    public static final int AUTOMANUAL = AttributesEnum.AutoManual.index();
    public static final int STARTTIME = AttributesEnum.StartTime.index();
    public static final int ENDTIME = AttributesEnum.EndTime.index();
    public static final int MARKERID = AttributesEnum.MarkerId.index();
    public static final int PLANYDS = AttributesEnum.PlanYds.index();
    public static final int PLANINCH = AttributesEnum.PlanInch.index();
    public static final int PLANMETER = AttributesEnum.PlanMeter.index();
    public static final int ACTUALYDS = AttributesEnum.ActualYds.index();
    public static final int ACTUALINCH = AttributesEnum.ActualInch.index();
    public static final int ACTUALMETER = AttributesEnum.ActualMeter.index();
    public static final int TIMECAL = AttributesEnum.TimeCal.index();
    public static final int USEDTIMEINMINUTES = AttributesEnum.UsedTimeInMinutes.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int INCHES = AttributesEnum.Inches.index();
    public static final int YARDS = AttributesEnum.Yards.index();
    public static final int CUTNOLOV1 = AttributesEnum.cutNoLov1.index();
    public static final int AUTO_MANUL1 = AttributesEnum.Auto_manul1.index();
    public static final int MARKERIDLOV1 = AttributesEnum.markeridLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LinesVORowImpl() {
    }

    /**
     * Gets LineEO entity object.
     * @return the LineEO
     */
    public LineEOImpl getLineEO() {
        return (LineEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DIVISION_ID using the alias name DivisionId.
     * @return the DIVISION_ID
     */
    public String getDivisionId() {
        return (String) getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_ID using the alias name DivisionId.
     * @param value value to set the DIVISION_ID
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for BUYER_ID using the alias name BuyerId.
     * @return the BUYER_ID
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYER_ID using the alias name BuyerId.
     * @param value value to set the BUYER_ID
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for CUT_NUMBER using the alias name CutNumber.
     * @return the CUT_NUMBER
     */
    public String getCutNumber() {
        return (String) getAttributeInternal(CUTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CUT_NUMBER using the alias name CutNumber.
     * @param value value to set the CUT_NUMBER
     */
    public void setCutNumber(String value) {
        setAttributeInternal(CUTNUMBER, value);
    }

    /**
     * Gets the attribute value for NO_OF_PLY using the alias name NoOfPly.
     * @return the NO_OF_PLY
     */
    public String getNoOfPly() {
        return (String) getAttributeInternal(NOOFPLY);
    }

    /**
     * Sets <code>value</code> as attribute value for NO_OF_PLY using the alias name NoOfPly.
     * @param value value to set the NO_OF_PLY
     */
    public void setNoOfPly(String value) {
        setAttributeInternal(NOOFPLY, value);
    }

    /**
     * Gets the attribute value for AUTO_MANUAL using the alias name AutoManual.
     * @return the AUTO_MANUAL
     */
    public String getAutoManual() {
        return (String) getAttributeInternal(AUTOMANUAL);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTO_MANUAL using the alias name AutoManual.
     * @param value value to set the AUTO_MANUAL
     */
    public void setAutoManual(String value) {
        setAttributeInternal(AUTOMANUAL, value);
    }

    /**
     * Gets the attribute value for START_TIME using the alias name StartTime.
     * @return the START_TIME
     */
    public Date getStartTime() {
        return (Date) getAttributeInternal(STARTTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for START_TIME using the alias name StartTime.
     * @param value value to set the START_TIME
     */
    public void setStartTime(Date value) {
        setAttributeInternal(STARTTIME, value);
    }

    /**
     * Gets the attribute value for END_TIME using the alias name EndTime.
     * @return the END_TIME
     */
    public Date getEndTime() {
        return (Date) getAttributeInternal(ENDTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for END_TIME using the alias name EndTime.
     * @param value value to set the END_TIME
     */
    public void setEndTime(Date value) {
        setAttributeInternal(ENDTIME, value);
    }

    /**
     * Gets the attribute value for MARKER_ID using the alias name MarkerId.
     * @return the MARKER_ID
     */
    public String getMarkerId() {
        return (String) getAttributeInternal(MARKERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MARKER_ID using the alias name MarkerId.
     * @param value value to set the MARKER_ID
     */
    public void setMarkerId(String value) {
        setAttributeInternal(MARKERID, value);
    }

    /**
     * Gets the attribute value for PLAN_YDS using the alias name PlanYds.
     * @return the PLAN_YDS
     */
    public String getPlanYds() {
        return (String) getAttributeInternal(PLANYDS);
    }

    /**
     * Sets <code>value</code> as attribute value for PLAN_YDS using the alias name PlanYds.
     * @param value value to set the PLAN_YDS
     */
    public void setPlanYds(String value) {
        setAttributeInternal(PLANYDS, value);
    }

    /**
     * Gets the attribute value for PLAN_INCH using the alias name PlanInch.
     * @return the PLAN_INCH
     */
    public String getPlanInch() {
        return (String) getAttributeInternal(PLANINCH);
    }

    /**
     * Sets <code>value</code> as attribute value for PLAN_INCH using the alias name PlanInch.
     * @param value value to set the PLAN_INCH
     */
    public void setPlanInch(String value) {
        setAttributeInternal(PLANINCH, value);
    }

    /**
     * Gets the attribute value for PLAN_METER using the alias name PlanMeter.
     * @return the PLAN_METER
     */
    public String getPlanMeter() {
        return (String) getAttributeInternal(PLANMETER);
    }

    /**
     * Sets <code>value</code> as attribute value for PLAN_METER using the alias name PlanMeter.
     * @param value value to set the PLAN_METER
     */
    public void setPlanMeter(String value) {
        setAttributeInternal(PLANMETER, value);
    }

    /**
     * Gets the attribute value for ACTUAL_YDS using the alias name ActualYds.
     * @return the ACTUAL_YDS
     */
    public String getActualYds() {
        return (String) getAttributeInternal(ACTUALYDS);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_YDS using the alias name ActualYds.
     * @param value value to set the ACTUAL_YDS
     */
    public void setActualYds(String value) {
        setAttributeInternal(ACTUALYDS, value);
    }

    /**
     * Gets the attribute value for ACTUAL_INCH using the alias name ActualInch.
     * @return the ACTUAL_INCH
     */
    public String getActualInch() {
        return (String) getAttributeInternal(ACTUALINCH);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_INCH using the alias name ActualInch.
     * @param value value to set the ACTUAL_INCH
     */
    public void setActualInch(String value) {
        setAttributeInternal(ACTUALINCH, value);
    }

    /**
     * Gets the attribute value for ACTUAL_METER using the alias name ActualMeter.
     * @return the ACTUAL_METER
     */
    public String getActualMeter() {
        return (String) getAttributeInternal(ACTUALMETER);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_METER using the alias name ActualMeter.
     * @param value value to set the ACTUAL_METER
     */
    public void setActualMeter(String value) {
        setAttributeInternal(ACTUALMETER, value);
    }

    /**
     * Gets the attribute value for TIME_CAL using the alias name TimeCal.
     * @return the TIME_CAL
     */
    public String getTimeCal() {
        return (String) getAttributeInternal(TIMECAL);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_CAL using the alias name TimeCal.
     * @param value value to set the TIME_CAL
     */
    public void setTimeCal(String value) {
        setAttributeInternal(TIMECAL, value);
    }

    /**
     * Gets the attribute value for USED_TIME_IN_MINUTES using the alias name UsedTimeInMinutes.
     * @return the USED_TIME_IN_MINUTES
     */
    public Date getUsedTimeInMinutes() {
        return (Date) getAttributeInternal(USEDTIMEINMINUTES);
    }

    /**
     * Sets <code>value</code> as attribute value for USED_TIME_IN_MINUTES using the alias name UsedTimeInMinutes.
     * @param value value to set the USED_TIME_IN_MINUTES
     */
    public void setUsedTimeInMinutes(Date value) {
        setAttributeInternal(USEDTIMEINMINUTES, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for INCHES using the alias name Inches.
     * @return the INCHES
     */
    public Number getInches() {
        return (Number) getAttributeInternal(INCHES);
    }

    /**
     * Sets <code>value</code> as attribute value for INCHES using the alias name Inches.
     * @param value value to set the INCHES
     */
    public void setInches(Number value) {
        setAttributeInternal(INCHES, value);
    }

    /**
     * Gets the attribute value for YARDS using the alias name Yards.
     * @return the YARDS
     */
    public Number getYards() {
        return (Number) getAttributeInternal(YARDS);
    }

    /**
     * Sets <code>value</code> as attribute value for YARDS using the alias name Yards.
     * @param value value to set the YARDS
     */
    public void setYards(Number value) {
        setAttributeInternal(YARDS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> cutNoLov1.
     */
    public RowSet getcutNoLov1() {
        return (RowSet)getAttributeInternal(CUTNOLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Auto_manul1.
     */
    public RowSet getAuto_manul1() {
        return (RowSet)getAttributeInternal(AUTO_MANUL1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> markeridLOV1.
     */
    public RowSet getmarkeridLOV1() {
        return (RowSet)getAttributeInternal(MARKERIDLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
