package mnj.mfg.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 31 16:24:09 PKT 2016
// ---------------------------------------------------------------------
public interface MainAM extends ApplicationModule {
    String getUnitName(String orgId);

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);
}
