package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 01 16:41:04 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class markeridLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public markeridLOVImpl() {
    }

    /**
     * Returns the variable value for p_markerid.
     * @return variable value for p_markerid
     */
    public String getp_markerid() {
        return (String)ensureVariableManager().getVariableValue("p_markerid");
    }

    /**
     * Sets <code>value</code> for variable p_markerid.
     * @param value value to bind as p_markerid
     */
    public void setp_markerid(String value) {
        ensureVariableManager().setVariableValue("p_markerid", value);
    }

    /**
     * Returns the bind variable value for p_org_id.
     * @return bind variable value for p_org_id
     */
    public String getp_org_id() {
        return (String)getNamedWhereClauseParam("p_org_id");
    }
}
