package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 31 16:04:32 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class operatingUnitsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public operatingUnitsVOImpl() {
    }
}
