package mnj.mfg.model.services;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import mnj.mfg.model.lov.operatingUnitsVOImpl;
import mnj.mfg.model.services.common.MainAM;
import mnj.mfg.model.views.LinesVOImpl;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 10 17:30:47 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MainAMImpl extends ApplicationModuleImpl implements MainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public MainAMImpl() {
    }

    /**
     * Container's getter for HeaderVO1.
     * @return HeaderVO1
     */
    public ViewObjectImpl getHeaderVO1() {
        return (ViewObjectImpl)findViewObject("HeaderVO1");
    }

    /**
     * Container's getter for LinesVO1.
     * @return LinesVO1
     */
    public LinesVOImpl getLinesVO1() {
        return (LinesVOImpl)findViewObject("LinesVO1");
    }

    /**
     * Container's getter for HeaderLineVL1.
     * @return HeaderLineVL1
     */
    public ViewLinkImpl getHeaderLineVL1() {
        return (ViewLinkImpl)findViewLink("HeaderLineVL1");
    }

    /**
     * Container's getter for operatingUnitsVO1.
     * @return operatingUnitsVO1
     */
    public operatingUnitsVOImpl getoperatingUnitsVO1() {
        return (operatingUnitsVOImpl)findViewObject("operatingUnitsVO1");
    }
    
    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
    
        

        if (userId != null) {
           //String flag = getFlagValue(userId, respId);
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession)ectx.getSession(false);
            //userSession.setAttribute("Flag", flag);
            userSession.setAttribute("userId", userId);
            userSession.setAttribute("orgId", orgId);
            userSession.setAttribute("respId", respId);
            userSession.setAttribute("unitName", getUnitName(orgId));
        }
    }


    public String getUnitName (String orgId){
        
        ViewObject vo = getoperatingUnitsVO1();
        vo.setWhereClause("ORGANIZATION_ID = "+orgId);
        vo.executeQuery();
        String name = null;
        vo.first();
        
        try {
            name = vo.getCurrentRow().getAttribute("Name").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return name ;
            
    }
    
    
    
    
    
}
